services:
  - type: static_site
    name: licoreria-elixir
    env: static
    branch: main
    nodeVersion: 20
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    root: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
